dist: xenial
os: linux
branches:
  except:
    - gh-pages
stages:
  - Build and test
  - Semantic release
  - Publish javadoc
  - Upload Archives

jobs:
  include:
    - stage: Build and test
      jdk: openjdk8
      language: java
      before_install:
        - .utility/decrypt-service-instance-apikeys.sh
      script:
        - ./gradlew checkstyleMain
        - ./gradlew checkstyleTest
        - travis_retry .utility/travis-run-tests.sh
      after_success:
        - bash <(curl -s https://codecov.io/bash)+++++++

    - stage: Semantic release
      jdk: openjdk8
      language: java
      if: (branch = master OR branch = rc) AND type = push AND fork = false
      before_install:
        - pip install --user bumpversion
        - nvm install 12
        - npm install @semantic-release/changelog
        - npm install @semantic-release/exec
        - npm install @semantic-release/git
      script:
        - npx semantic-release

    - stage: Publish javadoc
      jdk: openjdk8
      language: java
      if: type = push AND fork = false
      script:
        - ./gradlew docs
        - .utility/push-javadoc-to-gh-pages.sh

    - stage: Upload Archives
      jdk: openjdk8
      language: java
      if: tag IS present
      script:
        - .utility/deploy-travis-wrapper.sh

notifications:
  email: true
